"""Write the ``docsrc`` directory: a two-line ``conf.py`` shim and ``index.md``.

The directory is regenerated on every build, so committing it is optional. A
committed ``conf.py`` is overwritten only when it is one epythet generated
(the v2 shim or the 0.1.x template); a hand-written one is left alone and
reported.

>>> import tempfile, pathlib
>>> d = pathlib.Path(tempfile.mkdtemp())
>>> _ = (d / "pyproject.toml").write_text('[project]\\nname = "pkg"\\nversion = "0.1"\\n')
>>> _ = (d / "pkg").mkdir(); _ = (d / "pkg" / "__init__.py").write_text("")
>>> docsrc = make_docsrc(d, verbose=False)
>>> sorted(p.name for p in docsrc.iterdir())
['.gitignore', '_static', 'api.rst', 'conf.py', 'index.md']
>>> print((docsrc / "index.md").read_text())  # doctest: +ELLIPSIS
<!-- generated by epythet -->
<BLANKLINE>
# pkg
...
"""

import shutil
from pathlib import Path

from epythet import templates
from epythet.confgen import api_toctree_entry
from epythet.config import DocsConfig, load_config

README_CANDIDATES = ("README.md", "README.rst", "README.txt", "README")
#: Files and directories the 0.1.x generator wrote, removed when found.
LEGACY_GENERATED = ("table_of_contents.rst", "module_docs", "Makefile", "make.bat")
#: Build products of the API generators, removed so a build never keeps stale pages.
GENERATED_API_DIRS = ("_autosummary", "api")


def make_docsrc(project_dir, *, verbose: bool = True, ignore: list[str] = None) -> Path:
    """Create (or refresh) ``PROJECT_DIR/docsrc`` from the project's configuration.

    :param project_dir: the project root, holding ``pyproject.toml`` or ``setup.cfg``
    :param verbose: print what is written
    :param ignore: path substrings to skip, overriding ``[tool.epythet] ignore``
    :return: the docsrc directory
    """
    config = load_config(project_dir, ignore=ignore or None)
    return scaffold(config, verbose=verbose)


def scaffold(config: DocsConfig, *, verbose: bool = True) -> Path:
    """Write the docsrc files for an already-loaded configuration."""
    docsrc = config.docsrc_dir
    docsrc.mkdir(parents=True, exist_ok=True)
    (docsrc / "_static").mkdir(exist_ok=True)
    say = print if verbose else (lambda *a, **k: None)

    _remove_legacy_files(docsrc, say)
    for name in GENERATED_API_DIRS:
        if (docsrc / name).is_dir():
            shutil.rmtree(docsrc / name)
    _write_if_generated(
        docsrc / "conf.py",
        templates.conf_py_shim,
        markers=(templates.CONF_SHIM_MARKER, templates.LEGACY_CONF_MARKER),
        say=say,
    )
    _write_if_generated(
        docsrc / "index.md",
        render_index_md(config),
        markers=(templates.INDEX_MARKER,),
        say=say,
    )
    if config.api_generator == "autosummary":
        (docsrc / "api.rst").write_text(
            templates.api_rst_autosummary.format(package_name=config.package_name),
            encoding="utf-8",
        )
    gitignore = docsrc / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(templates.docsrc_gitignore, encoding="utf-8")
    return docsrc


def render_index_md(config: DocsConfig) -> str:
    """The landing page: the README included verbatim, plus a hidden API toctree."""
    readme = find_readme(config.project_dir)
    api_entry = api_toctree_entry(config)
    aggregates_block = render_aggregates_block(config)
    if readme is None:
        return templates.index_md_without_readme.format(
            marker=templates.INDEX_MARKER,
            display_name=config.display_name,
            api_entry=api_entry,
            aggregates_block=aggregates_block,
        )
    return templates.index_md_with_readme.format(
        marker=templates.INDEX_MARKER,
        readme=readme.name,
        api_entry=api_entry,
        aggregates_block=aggregates_block,
    )


def render_aggregates_block(config: DocsConfig) -> str:
    """The landing-page line linking the ``<package>.md`` / ``.pdf`` twins ('' when off)."""
    if not (config.agent_outputs and config.aggregates):
        return ""
    links = ", ".join(
        templates.aggregate_link.format(
            filename=f"{config.name}.{kind}",
            description=templates.AGGREGATE_DESCRIPTIONS[kind],
        )
        for kind in config.aggregates
    )
    return templates.aggregates_block.format(links=links)


def find_readme(project_dir: str | Path) -> Path | None:
    """The project's README file, if any (``README.md`` preferred).

    >>> find_readme("/nonexistent") is None
    True
    """
    project_dir = Path(project_dir)
    for name in README_CANDIDATES:
        candidate = project_dir / name
        if candidate.is_file():
            return candidate
    return None


def make_autodocs(
    project_dir,
    *,
    output_dirname: str = "module_docs",
    skip_existing: bool = True,
    docsrc_dir=None,
    ignore: list[str] = None,
) -> Path:
    """Compatibility entry point: API pages are now generated at build time.

    Kept because ``epythet make-autodocs`` and ``epythet.make_autodocs`` are
    called by older workflows. It (re)writes the docsrc scaffold and returns the
    docsrc directory; ``output_dirname``, ``skip_existing`` and ``docsrc_dir``
    are accepted for signature compatibility and ignored.

    :param project_dir: the project root
    :param ignore: path substrings to skip, overriding ``[tool.epythet] ignore``
    """
    return make_docsrc(project_dir, verbose=False, ignore=ignore)


def _remove_legacy_files(docsrc: Path, say) -> None:
    index_rst = docsrc / "index.rst"
    if index_rst.is_file() and "table_of_contents.rst" in index_rst.read_text(
        encoding="utf-8", errors="replace"
    ):
        index_rst.unlink()
        say(f"Removed legacy {index_rst.name} (index.md replaces it)")
    for name in LEGACY_GENERATED:
        path = docsrc / name
        if path.is_dir():
            shutil.rmtree(path)
            say(f"Removed legacy {name}/")
        elif path.is_file():
            path.unlink()
            say(f"Removed legacy {name}")


def _write_if_generated(path: Path, content: str, *, markers, say) -> None:
    if path.exists():
        existing = path.read_text(encoding="utf-8", errors="replace")
        if not any(marker in existing for marker in markers):
            say(f"Keeping hand-written {path.name} (no epythet marker found)")
            return
        if existing == content:
            return
    path.write_text(content, encoding="utf-8")
    say(f"Wrote {path}")
