"""Text templates for the generated ``docsrc`` files.

Only two files are generated: the ``conf.py`` shim and the ``index.md`` landing
page. Everything else (the API tree, the agent twins) is produced by Sphinx
extensions at build time.
"""

#: Marker line present in every conf.py epythet generated (v2), used to decide
#: whether an existing file may be overwritten.
CONF_SHIM_MARKER = "from epythet.sphinx_conf import *"

#: The old (0.1.x) template's signature line, also safe to overwrite.
LEGACY_CONF_MARKER = "from epythet.config_parser import parse_config"

conf_py_shim = '''\
"""Sphinx configuration, generated by epythet.

Settings come from ``[tool.epythet]`` in pyproject.toml (or ``[metadata]`` in
setup.cfg). Put project-specific overrides below the import; anything defined
here wins over the generated value.
"""

from epythet.sphinx_conf import *  # noqa: F401,F403
'''

#: Marker in the generated index.md, used to decide whether to overwrite it.
INDEX_MARKER = "<!-- generated by epythet -->"

index_md_with_readme = """\
{marker}

```{{include}} ../{readme}
:relative-images:
:relative-docs: ..
```

{aggregates_block}
```{{toctree}}
:maxdepth: 3
:hidden:

{toctree_entries}
```
"""

index_md_without_readme = """\
{marker}

# {display_name}

{aggregates_block}
```{{toctree}}
:maxdepth: 3

{toctree_entries}
```
"""

#: Footer of the landing page pointing at the single-document twins. Raw HTML,
#: because MyST would read a relative ``.md`` link as a (missing) page reference.
aggregates_block = """\
<p class="epythet-aggregates">This documentation as a single file: {links}.</p>
"""

aggregate_link = '<a href="{filename}">{filename}</a> ({description})'
AGGREGATE_DESCRIPTIONS = {"md": "Markdown, for agents", "pdf": "PDF, for reading"}

api_rst_autosummary = """\
API reference
=============

.. autosummary::
   :toctree: _autosummary
   :recursive:

   {package_name}
"""

#: What 0.1.x wrote to docsrc/.gitignore; safe to replace.
LEGACY_DOCSRC_GITIGNORES = ("_build/", "_build")

#: autosummary's stock ``module.rst`` (Sphinx 9) with one addition: submodules
#: matching the ignore fragments are left out of the recursion, so no stub is
#: generated (and no second import attempted) for tests/, scrap/, examples/.
autosummary_module_rst = """\
{{{{ fullname | escape | underline}}}}

.. automodule:: {{{{ fullname }}}}

   {{% block attributes %}}
   {{%- if attributes %}}
   .. rubric:: {{{{ _('Module Attributes') }}}}

   .. autosummary::
   {{% for item in attributes %}}
      {{{{ item }}}}
   {{%- endfor %}}
   {{% endif %}}
   {{%- endblock %}}

   {{%- block functions %}}
   {{%- if functions %}}
   .. rubric:: {{{{ _('Functions') }}}}

   .. autosummary::
   {{% for item in functions %}}
      {{{{ item }}}}
   {{%- endfor %}}
   {{% endif %}}
   {{%- endblock %}}

   {{%- block classes %}}
   {{%- if classes %}}
   .. rubric:: {{{{ _('Classes') }}}}

   .. autosummary::
   {{% for item in classes %}}
      {{{{ item }}}}
   {{%- endfor %}}
   {{% endif %}}
   {{%- endblock %}}

   {{%- block exceptions %}}
   {{%- if exceptions %}}
   .. rubric:: {{{{ _('Exceptions') }}}}

   .. autosummary::
   {{% for item in exceptions %}}
      {{{{ item }}}}
   {{%- endfor %}}
   {{% endif %}}
   {{%- endblock %}}

{{%- block modules %}}
{{%- set ignored = {ignored_fragments} %}}
{{%- set ns = namespace(kept=[]) %}}
{{%- for item in modules %}}
{{%- if not (ignored | select("in", '.' ~ item ~ '.') | list) %}}
{{%- set ns.kept = ns.kept + [item] %}}
{{%- endif %}}
{{%- endfor %}}
{{%- if ns.kept %}}
.. rubric:: Modules

.. autosummary::
   :toctree:
   :recursive:
{{% for item in ns.kept %}}
   {{{{ item }}}}
{{%- endfor %}}
{{% endif %}}
{{%- endblock %}}
"""

docsrc_gitignore = """\
# Generated by epythet at build time
_build/
api/
_autosummary/
_templates/
_static/epythet.css
"""
