"""Text templates for the generated ``docsrc`` files.

Only two files are generated: the ``conf.py`` shim and the ``index.md`` landing
page. Everything else (the API tree, the agent twins) is produced by Sphinx
extensions at build time.
"""

#: Marker line present in every conf.py epythet generated (v2), used to decide
#: whether an existing file may be overwritten.
CONF_SHIM_MARKER = "from epythet.sphinx_conf import *"

#: The old (0.1.x) template's signature line, also safe to overwrite.
LEGACY_CONF_MARKER = "from epythet.config_parser import parse_config"

conf_py_shim = '''\
"""Sphinx configuration, generated by epythet.

Settings come from ``[tool.epythet]`` in pyproject.toml (or ``[metadata]`` in
setup.cfg). Put project-specific overrides below the import; anything defined
here wins over the generated value.
"""

from epythet.sphinx_conf import *  # noqa: F401,F403
'''

#: Marker in the generated index.md, used to decide whether to overwrite it.
INDEX_MARKER = "<!-- generated by epythet -->"

index_md_with_readme = """\
{marker}

```{{include}} ../{readme}
:relative-images:
:relative-docs: ..
```

{aggregates_block}
```{{toctree}}
:maxdepth: 3
:hidden:

{api_entry}
```
"""

index_md_without_readme = """\
{marker}

# {display_name}

{aggregates_block}
```{{toctree}}
:maxdepth: 3

{api_entry}
```
"""

#: Footer of the landing page pointing at the single-document twins. Raw HTML,
#: because MyST would read a relative ``.md`` link as a (missing) page reference.
aggregates_block = """\
<p class="epythet-aggregates">This documentation as a single file: {links}.</p>
"""

aggregate_link = '<a href="{filename}">{filename}</a> ({description})'
AGGREGATE_DESCRIPTIONS = {"md": "Markdown, for agents", "pdf": "PDF, for reading"}

api_rst_autosummary = """\
API reference
=============

.. autosummary::
   :toctree: _autosummary
   :recursive:

   {package_name}
"""

docsrc_gitignore = """\
# Generated by epythet at build time
_build/
api/
_autosummary/
_static/epythet.css
"""
