"""Tests for the AI artifacts: shipped skills and agents, discovery, and the generated page.

Three concerns, in order: the artifacts epythet itself ships are spec-valid
(the Agent Skills frontmatter rules, and the subagent frontmatter), discovery
finds every artifact kind from a fixture repository (including through the
``.claude/skills`` symlink bridge, without duplicates), and the "For AI agents"
page is generated by default and builds in the smoke site.
"""

import os
import re
import shutil
from pathlib import Path

import pytest

from epythet import PageSpec, discover_artifacts
from epythet.ai_artifacts import (
    DEFAULT_TEMPLATE,
    PAGE_FILENAME,
    agent_outputs_for,
    ai_artifacts_page,
    artifacts_json,
    artifacts_table,
    default_pages,
    parse_frontmatter,
    render_ai_artifacts_page,
    repo_stub_for,
    site_url_for,
)
from epythet.config import DocsConfig, load_config
from epythet.scaffold import scaffold
from epythet.templates import INDEX_MARKER

REPO_ROOT = Path(__file__).resolve().parent.parent
SKILLS_DIR = REPO_ROOT / "epythet" / "data" / "skills"
AGENTS_DIR = REPO_ROOT / "epythet" / "data" / "agents"

SHIPPED_SKILLS = {
    "epythet-setup",
    "epythet-pages",
    "epythet-docstring-style",
    "epythet-validate",
    "epythet-repair-migrate",
    "epythet-theme",
    "epythet-ai-artifacts",
}
SHIPPED_AGENTS = {"docs-reviewer", "docs-migrator"}

#: The Agent Skills spec: the only top-level frontmatter keys allowed.
SPEC_KEYS = {
    "name",
    "description",
    "license",
    "compatibility",
    "metadata",
    "allowed-tools",
}
NAME_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")


# --------------------------------------------------------------------------
# The shipped artifacts are spec-valid
# --------------------------------------------------------------------------


def test_every_expected_skill_ships():
    assert {p.name for p in SKILLS_DIR.iterdir() if p.is_dir()} == SHIPPED_SKILLS


@pytest.mark.parametrize(
    "skill_dir", sorted(SKILLS_DIR.iterdir()), ids=lambda p: p.name
)
def test_skill_frontmatter_is_spec_clean(skill_dir):
    skill_md = skill_dir / "SKILL.md"
    assert skill_md.is_file()
    text = skill_md.read_text(encoding="utf-8")
    meta = parse_frontmatter(text)
    assert meta, "SKILL.md needs a YAML frontmatter"
    assert set(meta) <= SPEC_KEYS, f"non-spec keys: {set(meta) - SPEC_KEYS}"
    assert meta["name"] == skill_dir.name
    assert NAME_RE.match(meta["name"]) and len(meta["name"]) <= 64
    assert 1 <= len(meta["description"]) <= 1024
    assert meta["metadata"]["audience"] in ("users", "both")
    if "allowed-tools" in meta:
        assert isinstance(meta["allowed-tools"], str)
    body = text.split("---", 2)[2]
    assert body.count("\n") < 500, (
        "keep SKILL.md under 500 lines; push detail to references/"
    )
    assert body.strip(), "SKILL.md needs a body"


@pytest.mark.parametrize(
    "skill_dir", sorted(SKILLS_DIR.iterdir()), ids=lambda p: p.name
)
def test_skill_references_exist(skill_dir):
    """Relative links inside a SKILL.md point at files that ship with it."""
    text = (skill_dir / "SKILL.md").read_text(encoding="utf-8")
    for target in re.findall(r"\]\((?!https?://|#)([^)]+)\)", text):
        if "/" not in target and "." not in target:
            continue  # prose mentioning the `[text](url)` pattern, not a link
        assert (skill_dir / target).is_file(), f"{skill_dir.name}: missing {target}"


def test_every_expected_agent_ships_with_frontmatter():
    agents = {p.stem: parse_frontmatter(p.read_text()) for p in AGENTS_DIR.glob("*.md")}
    assert set(agents) == SHIPPED_AGENTS
    for name, meta in agents.items():
        assert meta["name"] == name
        assert len(meta["description"]) > 40
        assert meta["tools"]


def test_claude_code_bridge_symlinks_point_at_the_shipped_files():
    """One relative symlink per artifact in .claude/, never real copies."""
    for name in SHIPPED_SKILLS:
        link = REPO_ROOT / ".claude" / "skills" / name
        assert link.is_symlink(), f".claude/skills/{name} must be a symlink"
        assert not os.path.isabs(os.readlink(link))
        assert link.resolve() == (SKILLS_DIR / name).resolve()
    for name in SHIPPED_AGENTS:
        link = REPO_ROOT / ".claude" / "agents" / f"{name}.md"
        assert link.is_symlink()
        assert link.resolve() == (AGENTS_DIR / f"{name}.md").resolve()


def test_skill_cli_validator_agrees_if_installed():
    skill = pytest.importorskip("skill")
    for skill_dir in SKILLS_DIR.iterdir():
        assert skill.validate(str(skill_dir)) == [], skill_dir.name


# --------------------------------------------------------------------------
# Discovery
# --------------------------------------------------------------------------

SKILL_MD = "---\nname: {name}\ndescription: >-\n  Use {name} for things.\nmetadata:\n  audience: users\n---\n\n# {name}\n"
AGENT_MD = "---\nname: {name}\ndescription: Does {name} work.\ntools: Bash, Read\n---\n\nPrompt.\n"


def _write(path: Path, text: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


@pytest.fixture
def repo(tmp_path) -> Path:
    """A repository with every artifact kind, plus the .claude symlink bridge."""
    root = tmp_path / "acme"
    _write(
        root / "pyproject.toml",
        '[project]\nname = "acme"\nversion = "1.0"\n[project.urls]\nHomepage = "https://github.com/org/acme"\n',
    )
    _write(root / "acme" / "__init__.py", '"""Acme."""\n')
    _write(
        root / "acme" / "data" / "skills" / "acme-use" / "SKILL.md",
        SKILL_MD.format(name="acme-use"),
    )
    _write(
        root / "skills" / "acme-dev-release" / "SKILL.md",
        SKILL_MD.format(name="acme-dev-release"),
    )
    _write(
        root / ".claude" / "skills" / "acme-local" / "SKILL.md",
        SKILL_MD.format(name="acme-local"),
    )
    (root / ".claude" / "skills" / "acme-use").symlink_to(
        Path("../../acme/data/skills/acme-use")
    )
    _write(
        root / "acme" / "data" / "agents" / "acme-helper.md",
        AGENT_MD.format(name="acme-helper"),
    )
    _write(
        root / ".claude" / "agents" / "acme-local-agent.md",
        AGENT_MD.format(name="acme-local-agent"),
    )
    (root / ".claude" / "agents" / "acme-helper.md").symlink_to(
        Path("../../acme/data/agents/acme-helper.md")
    )
    _write(root / "CLAUDE.md", "# Acme\n")
    _write(root / "AGENTS.md", "# Agents\n")
    _write(root / ".cursor" / "rules" / "acme.mdc", "rule\n")
    _write(root / ".codex" / "config.toml", "x = 1\n")
    return root


def test_discovery_finds_each_kind_once(repo):
    found = discover_artifacts(repo, package_dir=repo / "acme")
    assert bool(found)
    by_name = {s.name: s for s in found.skills}
    assert set(by_name) == {"acme-use", "acme-dev-release", "acme-local"}
    assert by_name["acme-use"].source == "acme/data/skills/acme-use"
    assert by_name["acme-use"].shipped and by_name["acme-use"].installable
    assert by_name["acme-dev-release"].source == "skills/acme-dev-release"
    assert (
        not by_name["acme-dev-release"].shipped
        and by_name["acme-dev-release"].installable
    )
    assert by_name["acme-local"].source == ".claude/skills/acme-local"
    assert not by_name["acme-local"].installable
    assert by_name["acme-use"].description == "Use acme-use for things."
    assert by_name["acme-use"].audience == "users"

    agents = {a.name: a for a in found.subagents}
    assert set(agents) == {"acme-helper", "acme-local-agent"}
    assert agents["acme-helper"].source == "acme/data/agents/acme-helper.md"
    assert agents["acme-helper"].shipped and agents["acme-helper"].tools == "Bash, Read"
    assert not agents["acme-local-agent"].shipped

    files = {f.source: f for f in found.instruction_files}
    assert set(files) == {"CLAUDE.md", "AGENTS.md", ".cursor/rules", ".codex"}
    assert files[".cursor/rules"].is_dir and not files["CLAUDE.md"].is_dir


def test_discovery_without_package_dir_skips_package_locations(repo):
    found = discover_artifacts(repo)
    assert {s.name for s in found.skills} == {
        "acme-dev-release",
        "acme-local",
        "acme-use",
    }
    # acme-use is still found, via the .claude symlink, but attributed to its real location
    assert (
        next(s for s in found.skills if s.name == "acme-use").source
        == "acme/data/skills/acme-use"
    )


def test_empty_repo_has_no_artifacts(tmp_path):
    found = discover_artifacts(tmp_path)
    assert not found and found.skills == () and found.instruction_files == ()


def test_install_command_and_urls():
    assert repo_stub_for("git@github.com:org/acme.git") == "org/acme"
    assert repo_stub_for("https://gitlab.com/org/acme") == ""
    assert site_url_for("https://github.com/org/acme") == "https://org.github.io/acme/"
    cfg = DocsConfig(
        project_dir="/tmp/x", name="acme", repo_url="https://github.com/org/acme"
    )
    outputs = {o.kind: o for o in agent_outputs_for(cfg)}
    assert outputs["aggregate_md"].url == "https://org.github.io/acme/acme.md"
    assert outputs["md_twins"].url == ""
    assert "aggregate_pdf" not in outputs
    quiet = DocsConfig(project_dir="/tmp/x", name="acme", agent_outputs=False)
    assert [o.kind for o in agent_outputs_for(quiet)] == ["objects_inv"]


def test_frontmatter_fallback_parser_matches_yaml():
    text = SKILL_MD.format(name="x")
    expected = {
        "name": "x",
        "description": "Use x for things.",
        "metadata": {"audience": "users"},
    }
    assert parse_frontmatter(text) == expected
    from epythet.ai_artifacts import _parse_simple_yaml

    block = text.split("---")[1].strip("\n")
    assert _parse_simple_yaml(block) == expected


# --------------------------------------------------------------------------
# Rendering and the PageSpec seam
# --------------------------------------------------------------------------


def test_page_renders_every_section(repo):
    cfg = load_config(repo)
    page = ai_artifacts_page(cfg)
    assert isinstance(page, PageSpec) and page.filename == PAGE_FILENAME
    text = page.content
    assert text.startswith(INDEX_MARKER)
    assert "# For AI agents" in text
    assert "gh skill install org/acme acme-use --agent claude-code" in text
    assert "gh skill install org/acme acme-dev-release" in text
    assert (
        "gh skill install org/acme acme-local" not in text
    )  # hidden dir: not gh-installable
    assert "(bundled with the pip package)" in text
    assert "### `acme-helper`" in text and "tools: `Bash, Read`" in text
    assert "[`CLAUDE.md`](https://github.com/org/acme/tree/HEAD/CLAUDE.md)" in text
    assert "[`llms.txt`](https://org.github.io/acme/llms.txt)" in text
    assert "[`acme.md`](https://org.github.io/acme/acme.md)" in text
    assert "objects.inv" in text


def test_page_without_repo_url_uses_relative_links(repo):
    cfg = load_config(repo).with_overrides(repo_url="")
    text = render_ai_artifacts_page(
        discover_artifacts(repo, package_dir=cfg.package_dir), cfg
    )
    assert "gh skill install" not in text
    assert '<a href="llms.txt">' in text
    assert "`acme/data/skills/acme-use`" in text


def test_page_is_off_without_artifacts_or_when_disabled(repo, tmp_path):
    bare = tmp_path / "bare"
    _write(bare / "pyproject.toml", '[project]\nname = "bare"\n')
    _write(bare / "bare" / "__init__.py", "")
    assert ai_artifacts_page(load_config(bare)) is None
    assert default_pages(load_config(bare)) == []
    assert ai_artifacts_page(load_config(repo, ai_artifacts=False)) is None
    assert load_config(repo).ai_artifacts is True


def test_template_override_from_config(repo):
    _write(
        repo / "docsrc" / "_templates" / "agents.md",
        "# Robots for {display_name}\n{skills_section}",
    )
    cfg = load_config(repo, ai_artifacts_template="docsrc/_templates/agents.md")
    page = ai_artifacts_page(cfg)
    assert page.content.startswith(
        INDEX_MARKER
    )  # marker prepended so the file stays regenerable
    assert "# Robots for acme" in page.content and "acme-use" in page.content
    assert DEFAULT_TEMPLATE.count("{") >= 5


def test_scaffold_generates_the_page_by_default_and_keeps_hand_written(repo):
    cfg = load_config(repo)
    docsrc = scaffold(cfg, verbose=False)
    page = docsrc / PAGE_FILENAME
    assert page.is_file() and INDEX_MARKER in page.read_text()
    assert "\napi\nai-agents\n" in (docsrc / "index.md").read_text()
    page.write_text("# Mine\n")
    scaffold(cfg, verbose=False)
    assert page.read_text() == "# Mine\n"
    shutil.rmtree(docsrc)
    scaffold(cfg, verbose=False, pages=())
    assert not (docsrc / PAGE_FILENAME).exists()


def test_cli_renderers(repo):
    found = discover_artifacts(repo, package_dir=repo / "acme")
    table = artifacts_table(found, repo_stub="org/acme")
    assert "Skills (3)" in table and "gh skill install org/acme acme-use" in table
    import json

    data = json.loads(artifacts_json(found))
    assert {s["name"] for s in data["skills"]} == {
        "acme-use",
        "acme-dev-release",
        "acme-local",
    }


def test_epythet_documents_its_own_artifacts():
    cfg = load_config(REPO_ROOT)
    found = discover_artifacts(REPO_ROOT, package_dir=cfg.package_dir)
    assert {s.name for s in found.skills} == SHIPPED_SKILLS
    assert all(s.shipped and s.installable for s in found.skills)
    assert {a.name for a in found.subagents} == SHIPPED_AGENTS
    assert ".claude/CLAUDE.md" in {f.source for f in found.instruction_files}
    page = ai_artifacts_page(cfg)
    assert (
        "gh skill install i2mint/epythet epythet-setup --agent claude-code"
        in page.content
    )
    assert "https://i2mint.github.io/epythet/epythet.md" in page.content


# --------------------------------------------------------------------------
# Smoke build
# --------------------------------------------------------------------------


def test_page_builds_in_the_site(repo):
    from epythet.build import build

    cfg = load_config(repo)
    scaffold(cfg, verbose=False)
    html = build(cfg, "html")
    page = (html / "ai-agents.html").read_text(encoding="utf-8")
    assert "For AI agents" in page
    assert 'href="https://org.github.io/acme/llms.txt"' in page
    assert "ai-agents" in (html / "index.html").read_text(encoding="utf-8")
    # The page has its own agent twin; the install line is intact there (the
    # HTML splits it into highlighted spans).
    twin = (html / "ai-agents.html.md").read_text(encoding="utf-8")
    assert "gh skill install org/acme acme-use --agent claude-code" in twin
