"""Unit tests for :mod:`epythet.provenance`: collection, degradation, rendering.

The Sphinx smoke build in ``test_build.py`` covers the rendered footer, page
and JSON; here the record itself is exercised without a build: a git fixture
(clean, dirty, tagged, detached), the CI environment, no git at all, the JSON
key set that ``schema_version`` promises, and the ``provenance`` config seam.
"""

import json
import subprocess
from pathlib import Path

import pytest

from epythet.config import ConfigError, DocsConfig, load_config
from epythet.provenance import (
    ABOUT_PAGE_DOCNAME,
    SCHEMA_VERSION,
    alignment,
    ci_info,
    collect_build_info,
    compare_versions,
    footer_text,
    git_info,
    github_web_url,
    pypi_info,
    render_about_page,
    render_footer_line,
    strip_credentials,
)

GIT = ["git", "-c", "user.email=jane@example.com", "-c", "user.name=Jane"]


def _git(root, *args):
    return subprocess.run(
        [*GIT, *args], cwd=root, check=True, capture_output=True, text=True
    ).stdout.strip()


@pytest.fixture
def repo(make_project) -> Path:
    """A committed project with a GitHub remote and a tag on HEAD."""
    root = make_project("pkg", {"core.py": '"""Core."""\n'})
    (root / "docsrc").mkdir()
    (root / "docsrc" / "index.md").write_text("# committed docsrc\n")
    _git(root, "init", "-q", "-b", "main")
    _git(root, "add", "-A")
    _git(root, "commit", "-qm", "init")
    _git(root, "remote", "add", "origin", "git@github.com:org/pkg.git")
    _git(root, "tag", "v0.0.1")
    return root


# --------------------------------------------------------------------------
# git
# --------------------------------------------------------------------------


def test_git_info_clean_tagged_repo(repo):
    info = git_info(repo)
    assert info["available"] and info["error"] is None
    assert info["commit"] == _git(repo, "rev-parse", "HEAD")
    assert info["short_commit"] == info["commit"][:7]
    assert info["branch"] == "main" and info["tags"] == ["v0.0.1"]
    assert info["dirty"] is False
    assert info["remote_url"] == "git@github.com:org/pkg.git"
    assert info["commit_url"] == f"https://github.com/org/pkg/commit/{info['commit']}"


def test_git_info_dirty_flag_ignores_the_docs_dir(repo):
    # The build rewrites a committed docsrc/: that must not count as dirty.
    (repo / "docsrc" / "index.md").write_text("# regenerated by the build\n")
    assert git_info(repo, exclude=("docsrc/",))["dirty"] is False
    assert git_info(repo)["dirty"] is True
    (repo / "pkg" / "core.py").write_text('"""Changed."""\n')
    assert git_info(repo, exclude=("docsrc/",))["dirty"] is True


def test_git_info_untracked_files_do_not_count(repo):
    (repo / "scratch.txt").write_text("x")
    assert git_info(repo)["dirty"] is False


def test_git_info_detached_head_has_no_branch_name(repo):
    _git(repo, "checkout", "-q", "--detach")
    assert git_info(repo)["branch"] == "HEAD"


def test_git_info_without_a_repository(tmp_path):
    info = git_info(tmp_path)
    assert info["available"] is False and info["commit"] is None
    assert info["dirty"] is None and info["tags"] == []
    assert info["error"]


def test_github_web_url_forms():
    assert github_web_url("git@github.com:o/r.git") == "https://github.com/o/r"
    assert github_web_url("https://github.com/o/r") == "https://github.com/o/r"
    assert github_web_url("ssh://git@github.com/o/r.git") == "https://github.com/o/r"
    assert github_web_url("https://gitlab.com/o/r.git") is None


def test_remote_credentials_never_reach_the_record(repo):
    _git(
        repo, "remote", "set-url", "origin", "https://me:ghp_secret@github.com/o/r.git"
    )
    info = git_info(repo)
    assert "ghp_secret" not in json.dumps(info)
    assert info["remote_url"] == "https://github.com/o/r.git"
    assert strip_credentials("git@github.com:o/r.git") == "git@github.com:o/r.git"


# --------------------------------------------------------------------------
# CI and the full record
# --------------------------------------------------------------------------

CI_ENV = {
    "GITHUB_ACTIONS": "true",
    "GITHUB_REPOSITORY": "org/pkg",
    "GITHUB_RUN_ID": "123",
    "GITHUB_REF": "refs/heads/main",
    "GITHUB_REF_NAME": "main",
    "GITHUB_SERVER_URL": "https://github.com",
}


def test_ci_info_outside_ci_is_all_none():
    assert set(ci_info({}).values()) == {None}


def test_ci_context_fills_branch_and_commit_url_when_git_cannot(tmp_path, make_project):
    root = make_project("pkg", {})
    env = {**CI_ENV, "GITHUB_SHA": "a" * 40, "EPYTHET_PYPI_CHECK": "0"}
    info = collect_build_info(load_config(root), environ=env)
    assert info["ci"]["run_url"] == "https://github.com/org/pkg/actions/runs/123"
    assert info["git"]["available"] is False
    assert (
        info["git"]["commit"] == "a" * 40 and info["git"]["short_commit"] == "aaaaaaa"
    )
    assert info["git"]["branch"] == "main"
    assert info["git"]["commit_url"] == "https://github.com/org/pkg/commit/" + "a" * 40
    assert any(w.startswith("git:") for w in info["warnings"])


def test_ci_sha_mismatch_is_a_misalignment_note(repo):
    env = {**CI_ENV, "GITHUB_SHA": "b" * 40, "EPYTHET_PYPI_CHECK": "0"}
    info = collect_build_info(load_config(repo), environ=env)
    assert info["alignment"]["aligned"] is False
    assert any("CI checkout" in note for note in info["alignment"]["notes"])


EXPECTED_KEYS = {
    "schema_version",
    "built_at",
    "package",
    "git",
    "ci",
    "tools",
    "config",
    "site",
    "pypi",
    "reproduce",
    "warnings",
    "alignment",
}


def test_record_schema_is_stable_and_json_serialisable(repo):
    info = collect_build_info(load_config(repo), check_pypi=False)
    assert set(info) == EXPECTED_KEYS and info["schema_version"] == SCHEMA_VERSION
    assert set(info["package"]) == {"name", "version", "display_name", "source"}
    assert set(info["git"]) == {
        "available",
        "commit",
        "short_commit",
        "branch",
        "tags",
        "dirty",
        "remote_url",
        "commit_url",
        "error",
    }
    assert set(info["ci"]) == {
        "provider",
        "repository",
        "sha",
        "ref",
        "ref_name",
        "run_id",
        "run_url",
        "server_url",
    }
    assert set(info["tools"]) == {"epythet", "sphinx", "docutils", "python"}
    assert set(info["config"]) == {
        "theme",
        "html_theme",
        "accent",
        "mode",
        "api_generator",
        "ignore",
        "agent_outputs",
        "aggregates",
        "ai_artifacts",
        "provenance",
        "docs_dir",
    }
    assert set(info["site"]) == {"modules_documented", "objects_documented"}
    assert set(info["pypi"]) == {"checked", "latest", "relation", "error"}
    assert set(info["alignment"]) == {"aligned", "notes"}
    assert info["package"]["source"] == "pyproject.toml"
    assert info["built_at"].endswith("Z")
    assert info["alignment"] == {"aligned": True, "notes": []}
    assert "git checkout " + info["git"]["commit"] in info["reproduce"]
    json.dumps(info)  # every value is plain JSON


def test_record_without_git_says_so(make_project):
    info = collect_build_info(load_config(make_project("pkg", {})), check_pypi=False)
    assert info["git"]["available"] is False
    assert info["alignment"]["aligned"] is None
    assert "unknown" in info["alignment"]["notes"][-1]
    assert "git checkout" not in info["reproduce"]
    text = footer_text(info)
    assert text.startswith("built ") and " from " not in text and "pkg 0.0.1" in text


# --------------------------------------------------------------------------
# PyPI
# --------------------------------------------------------------------------


def test_compare_versions():
    assert compare_versions("0.2.4", "0.2.5") == "behind"
    assert compare_versions("0.3.0", "0.2.5") == "ahead"
    assert compare_versions("1.0", "1.0.0") == "same"
    assert compare_versions("not-a-version", "1.0") == "unknown"


def test_pypi_lookup_failure_degrades_to_not_checked(monkeypatch):
    import epythet.provenance as prov

    def boom(name, *, timeout):
        raise OSError("network is unreachable")

    monkeypatch.setattr(prov, "pypi_latest_version", boom)
    info = pypi_info("pkg", "1.0")
    assert info == {
        "checked": False,
        "latest": None,
        "relation": "unknown",
        "error": "OSError: network is unreachable",
    }


def test_pypi_behind_and_ahead_notes(monkeypatch, repo):
    import epythet.provenance as prov

    monkeypatch.setattr(prov, "pypi_latest_version", lambda name, *, timeout: "0.0.2")
    info = collect_build_info(load_config(repo), check_pypi=True)
    assert info["pypi"] == {
        "checked": True,
        "latest": "0.0.2",
        "relation": "behind",
        "error": None,
    }
    assert info["alignment"]["aligned"] is False
    assert "behind the latest release on PyPI (0.0.2)" in info["alignment"]["notes"][0]
    page = render_about_page(info)
    assert "newer than the documented version (0.0.1)" in page
    monkeypatch.setattr(prov, "pypi_latest_version", lambda name, *, timeout: None)
    info = collect_build_info(load_config(repo), check_pypi=True)
    assert (
        info["pypi"]["relation"] == "unknown" and info["alignment"]["aligned"] is True
    )
    assert "is not on PyPI" in render_about_page(info)


def test_pypi_env_switch(monkeypatch, repo):
    import epythet.provenance as prov

    calls = []
    monkeypatch.setattr(
        prov, "pypi_latest_version", lambda name, *, timeout: calls.append(name)
    )
    collect_build_info(load_config(repo), environ={"EPYTHET_PYPI_CHECK": "0"})
    assert calls == []
    collect_build_info(load_config(repo), environ={})
    assert calls == ["pkg"]


# --------------------------------------------------------------------------
# rendering
# --------------------------------------------------------------------------


def test_footer_line_html(repo):
    info = collect_build_info(load_config(repo), check_pypi=False)
    (repo / "pkg" / "core.py").write_text('"""Changed."""\n')
    dirty = collect_build_info(load_config(repo), check_pypi=False)
    line = render_footer_line(dirty)
    assert line.startswith('<p class="epythet-provenance"')
    assert (
        f'<a href="{dirty["git"]["commit_url"]}">{dirty["git"]["short_commit"]}+dirty</a> (main)'
        in line
    )
    assert "· pkg 0.0.1 ·" in line
    assert f'<a href="{ABOUT_PAGE_DOCNAME}.html">about this build</a>' in line
    assert "+dirty" not in render_footer_line(info)
    assert '<a href="build_info.json">build info</a>' in render_footer_line(
        info, about_href=None
    )


def test_about_page_content(repo):
    info = collect_build_info(
        load_config(repo),
        environ={**CI_ENV, "GITHUB_SHA": info_sha(repo)},
        check_pypi=False,
    )
    page = render_about_page(info)
    assert page.startswith("---\norphan: true\n---\n<!-- generated by epythet -->")
    assert ":::{note}" in page and "Nothing suggests a mismatch" in page
    assert "| Tags at this commit | `v0.0.1` |" in page
    assert "| Working tree | clean |" in page
    assert "[123](https://github.com/org/pkg/actions/runs/123)" in page
    assert "| ignore | `tests/`, `scrap/`, `examples/` |" in page
    assert "Not checked." in page
    assert '<a href="build_info.json">' in page


def info_sha(repo):
    return _git(repo, "rev-parse", "HEAD")


def test_about_page_custom_template_uses_a_subset_of_fields(repo):
    info = collect_build_info(load_config(repo), check_pypi=False)
    page = render_about_page(info, template="{marker}\n# Build\n\n{summary}\n")
    assert page.startswith("<!-- generated by epythet -->\n# Build")
    assert "pkg 0.0.1" in page


def test_alignment_dirty_note():
    info = {
        "git": {
            "available": True,
            "dirty": True,
            "commit": "c" * 40,
            "short_commit": "ccccccc",
        },
        "pypi": {"checked": False, "latest": None, "relation": "unknown"},
        "ci": {"sha": None},
        "package": {"name": "pkg", "version": "1"},
    }
    result = alignment(info)
    assert result["aligned"] is False and "uncommitted changes" in result["notes"][0]


# --------------------------------------------------------------------------
# the config seam
# --------------------------------------------------------------------------


@pytest.mark.parametrize(
    "value, expected",
    [("true", True), ("false", False), ('"minimal"', "minimal")],
)
def test_provenance_key_from_pyproject(tmp_path, value, expected):
    (tmp_path / "pyproject.toml").write_text(
        f'[project]\nname = "x"\n[tool.epythet]\nprovenance = {value}\n'
    )
    assert load_config(tmp_path).provenance == expected


@pytest.mark.parametrize(
    "value, expected",
    [("true", True), ("off", False), ("Minimal", "minimal")],
)
def test_provenance_key_from_setup_cfg(tmp_path, value, expected):
    (tmp_path / "setup.cfg").write_text(
        f"[metadata]\nname = x\n[tool.epythet]\nprovenance = {value}\n"
    )
    assert load_config(tmp_path).provenance == expected


def test_provenance_key_rejects_other_values():
    with pytest.raises(ConfigError, match="provenance"):
        DocsConfig(project_dir="/tmp/x", name="x", provenance="verbose")


def test_default_is_on():
    assert DocsConfig(project_dir="/tmp/x", name="x").provenance is True
